
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ReminderHistory` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ReminderHistory
 * 
 */
export type ReminderHistoryModel = runtime.Types.Result.DefaultSelection<Prisma.$ReminderHistoryPayload>

export type AggregateReminderHistory = {
  _count: ReminderHistoryCountAggregateOutputType | null
  _min: ReminderHistoryMinAggregateOutputType | null
  _max: ReminderHistoryMaxAggregateOutputType | null
}

export type ReminderHistoryMinAggregateOutputType = {
  id: string | null
  taskTitle: string | null
  templateName: string | null
  date: string | null
  time: string | null
  status: string | null
  sentAt: Date | null
  createdAt: Date | null
  taskId: string | null
  templateId: string | null
}

export type ReminderHistoryMaxAggregateOutputType = {
  id: string | null
  taskTitle: string | null
  templateName: string | null
  date: string | null
  time: string | null
  status: string | null
  sentAt: Date | null
  createdAt: Date | null
  taskId: string | null
  templateId: string | null
}

export type ReminderHistoryCountAggregateOutputType = {
  id: number
  taskTitle: number
  templateName: number
  date: number
  time: number
  status: number
  sentAt: number
  createdAt: number
  taskId: number
  templateId: number
  _all: number
}


export type ReminderHistoryMinAggregateInputType = {
  id?: true
  taskTitle?: true
  templateName?: true
  date?: true
  time?: true
  status?: true
  sentAt?: true
  createdAt?: true
  taskId?: true
  templateId?: true
}

export type ReminderHistoryMaxAggregateInputType = {
  id?: true
  taskTitle?: true
  templateName?: true
  date?: true
  time?: true
  status?: true
  sentAt?: true
  createdAt?: true
  taskId?: true
  templateId?: true
}

export type ReminderHistoryCountAggregateInputType = {
  id?: true
  taskTitle?: true
  templateName?: true
  date?: true
  time?: true
  status?: true
  sentAt?: true
  createdAt?: true
  taskId?: true
  templateId?: true
  _all?: true
}

export type ReminderHistoryAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ReminderHistory to aggregate.
   */
  where?: Prisma.ReminderHistoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ReminderHistories to fetch.
   */
  orderBy?: Prisma.ReminderHistoryOrderByWithRelationInput | Prisma.ReminderHistoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ReminderHistoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ReminderHistories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ReminderHistories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ReminderHistories
  **/
  _count?: true | ReminderHistoryCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ReminderHistoryMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ReminderHistoryMaxAggregateInputType
}

export type GetReminderHistoryAggregateType<T extends ReminderHistoryAggregateArgs> = {
      [P in keyof T & keyof AggregateReminderHistory]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateReminderHistory[P]>
    : Prisma.GetScalarType<T[P], AggregateReminderHistory[P]>
}




export type ReminderHistoryGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ReminderHistoryWhereInput
  orderBy?: Prisma.ReminderHistoryOrderByWithAggregationInput | Prisma.ReminderHistoryOrderByWithAggregationInput[]
  by: Prisma.ReminderHistoryScalarFieldEnum[] | Prisma.ReminderHistoryScalarFieldEnum
  having?: Prisma.ReminderHistoryScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ReminderHistoryCountAggregateInputType | true
  _min?: ReminderHistoryMinAggregateInputType
  _max?: ReminderHistoryMaxAggregateInputType
}

export type ReminderHistoryGroupByOutputType = {
  id: string
  taskTitle: string
  templateName: string | null
  date: string
  time: string
  status: string
  sentAt: Date | null
  createdAt: Date
  taskId: string
  templateId: string | null
  _count: ReminderHistoryCountAggregateOutputType | null
  _min: ReminderHistoryMinAggregateOutputType | null
  _max: ReminderHistoryMaxAggregateOutputType | null
}

export type GetReminderHistoryGroupByPayload<T extends ReminderHistoryGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ReminderHistoryGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ReminderHistoryGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ReminderHistoryGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ReminderHistoryGroupByOutputType[P]>
      }
    >
  >



export type ReminderHistoryWhereInput = {
  AND?: Prisma.ReminderHistoryWhereInput | Prisma.ReminderHistoryWhereInput[]
  OR?: Prisma.ReminderHistoryWhereInput[]
  NOT?: Prisma.ReminderHistoryWhereInput | Prisma.ReminderHistoryWhereInput[]
  id?: Prisma.StringFilter<"ReminderHistory"> | string
  taskTitle?: Prisma.StringFilter<"ReminderHistory"> | string
  templateName?: Prisma.StringNullableFilter<"ReminderHistory"> | string | null
  date?: Prisma.StringFilter<"ReminderHistory"> | string
  time?: Prisma.StringFilter<"ReminderHistory"> | string
  status?: Prisma.StringFilter<"ReminderHistory"> | string
  sentAt?: Prisma.DateTimeNullableFilter<"ReminderHistory"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"ReminderHistory"> | Date | string
  taskId?: Prisma.StringFilter<"ReminderHistory"> | string
  templateId?: Prisma.StringNullableFilter<"ReminderHistory"> | string | null
  task?: Prisma.XOR<Prisma.TaskScalarRelationFilter, Prisma.TaskWhereInput>
  template?: Prisma.XOR<Prisma.TemplateNullableScalarRelationFilter, Prisma.TemplateWhereInput> | null
}

export type ReminderHistoryOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  taskTitle?: Prisma.SortOrder
  templateName?: Prisma.SortOrderInput | Prisma.SortOrder
  date?: Prisma.SortOrder
  time?: Prisma.SortOrder
  status?: Prisma.SortOrder
  sentAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  taskId?: Prisma.SortOrder
  templateId?: Prisma.SortOrderInput | Prisma.SortOrder
  task?: Prisma.TaskOrderByWithRelationInput
  template?: Prisma.TemplateOrderByWithRelationInput
}

export type ReminderHistoryWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.ReminderHistoryWhereInput | Prisma.ReminderHistoryWhereInput[]
  OR?: Prisma.ReminderHistoryWhereInput[]
  NOT?: Prisma.ReminderHistoryWhereInput | Prisma.ReminderHistoryWhereInput[]
  taskTitle?: Prisma.StringFilter<"ReminderHistory"> | string
  templateName?: Prisma.StringNullableFilter<"ReminderHistory"> | string | null
  date?: Prisma.StringFilter<"ReminderHistory"> | string
  time?: Prisma.StringFilter<"ReminderHistory"> | string
  status?: Prisma.StringFilter<"ReminderHistory"> | string
  sentAt?: Prisma.DateTimeNullableFilter<"ReminderHistory"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"ReminderHistory"> | Date | string
  taskId?: Prisma.StringFilter<"ReminderHistory"> | string
  templateId?: Prisma.StringNullableFilter<"ReminderHistory"> | string | null
  task?: Prisma.XOR<Prisma.TaskScalarRelationFilter, Prisma.TaskWhereInput>
  template?: Prisma.XOR<Prisma.TemplateNullableScalarRelationFilter, Prisma.TemplateWhereInput> | null
}, "id">

export type ReminderHistoryOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  taskTitle?: Prisma.SortOrder
  templateName?: Prisma.SortOrderInput | Prisma.SortOrder
  date?: Prisma.SortOrder
  time?: Prisma.SortOrder
  status?: Prisma.SortOrder
  sentAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  taskId?: Prisma.SortOrder
  templateId?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.ReminderHistoryCountOrderByAggregateInput
  _max?: Prisma.ReminderHistoryMaxOrderByAggregateInput
  _min?: Prisma.ReminderHistoryMinOrderByAggregateInput
}

export type ReminderHistoryScalarWhereWithAggregatesInput = {
  AND?: Prisma.ReminderHistoryScalarWhereWithAggregatesInput | Prisma.ReminderHistoryScalarWhereWithAggregatesInput[]
  OR?: Prisma.ReminderHistoryScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ReminderHistoryScalarWhereWithAggregatesInput | Prisma.ReminderHistoryScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ReminderHistory"> | string
  taskTitle?: Prisma.StringWithAggregatesFilter<"ReminderHistory"> | string
  templateName?: Prisma.StringNullableWithAggregatesFilter<"ReminderHistory"> | string | null
  date?: Prisma.StringWithAggregatesFilter<"ReminderHistory"> | string
  time?: Prisma.StringWithAggregatesFilter<"ReminderHistory"> | string
  status?: Prisma.StringWithAggregatesFilter<"ReminderHistory"> | string
  sentAt?: Prisma.DateTimeNullableWithAggregatesFilter<"ReminderHistory"> | Date | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ReminderHistory"> | Date | string
  taskId?: Prisma.StringWithAggregatesFilter<"ReminderHistory"> | string
  templateId?: Prisma.StringNullableWithAggregatesFilter<"ReminderHistory"> | string | null
}

export type ReminderHistoryCreateInput = {
  id?: string
  taskTitle: string
  templateName?: string | null
  date: string
  time: string
  status: string
  sentAt?: Date | string | null
  createdAt?: Date | string
  task: Prisma.TaskCreateNestedOneWithoutReminderHistoriesInput
  template?: Prisma.TemplateCreateNestedOneWithoutReminderHistoriesInput
}

export type ReminderHistoryUncheckedCreateInput = {
  id?: string
  taskTitle: string
  templateName?: string | null
  date: string
  time: string
  status: string
  sentAt?: Date | string | null
  createdAt?: Date | string
  taskId: string
  templateId?: string | null
}

export type ReminderHistoryUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  taskTitle?: Prisma.StringFieldUpdateOperationsInput | string
  templateName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  date?: Prisma.StringFieldUpdateOperationsInput | string
  time?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  sentAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  task?: Prisma.TaskUpdateOneRequiredWithoutReminderHistoriesNestedInput
  template?: Prisma.TemplateUpdateOneWithoutReminderHistoriesNestedInput
}

export type ReminderHistoryUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  taskTitle?: Prisma.StringFieldUpdateOperationsInput | string
  templateName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  date?: Prisma.StringFieldUpdateOperationsInput | string
  time?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  sentAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  taskId?: Prisma.StringFieldUpdateOperationsInput | string
  templateId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ReminderHistoryCreateManyInput = {
  id?: string
  taskTitle: string
  templateName?: string | null
  date: string
  time: string
  status: string
  sentAt?: Date | string | null
  createdAt?: Date | string
  taskId: string
  templateId?: string | null
}

export type ReminderHistoryUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  taskTitle?: Prisma.StringFieldUpdateOperationsInput | string
  templateName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  date?: Prisma.StringFieldUpdateOperationsInput | string
  time?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  sentAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ReminderHistoryUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  taskTitle?: Prisma.StringFieldUpdateOperationsInput | string
  templateName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  date?: Prisma.StringFieldUpdateOperationsInput | string
  time?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  sentAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  taskId?: Prisma.StringFieldUpdateOperationsInput | string
  templateId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ReminderHistoryListRelationFilter = {
  every?: Prisma.ReminderHistoryWhereInput
  some?: Prisma.ReminderHistoryWhereInput
  none?: Prisma.ReminderHistoryWhereInput
}

export type ReminderHistoryOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ReminderHistoryCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  taskTitle?: Prisma.SortOrder
  templateName?: Prisma.SortOrder
  date?: Prisma.SortOrder
  time?: Prisma.SortOrder
  status?: Prisma.SortOrder
  sentAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  taskId?: Prisma.SortOrder
  templateId?: Prisma.SortOrder
}

export type ReminderHistoryMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  taskTitle?: Prisma.SortOrder
  templateName?: Prisma.SortOrder
  date?: Prisma.SortOrder
  time?: Prisma.SortOrder
  status?: Prisma.SortOrder
  sentAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  taskId?: Prisma.SortOrder
  templateId?: Prisma.SortOrder
}

export type ReminderHistoryMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  taskTitle?: Prisma.SortOrder
  templateName?: Prisma.SortOrder
  date?: Prisma.SortOrder
  time?: Prisma.SortOrder
  status?: Prisma.SortOrder
  sentAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  taskId?: Prisma.SortOrder
  templateId?: Prisma.SortOrder
}

export type ReminderHistoryCreateNestedManyWithoutTemplateInput = {
  create?: Prisma.XOR<Prisma.ReminderHistoryCreateWithoutTemplateInput, Prisma.ReminderHistoryUncheckedCreateWithoutTemplateInput> | Prisma.ReminderHistoryCreateWithoutTemplateInput[] | Prisma.ReminderHistoryUncheckedCreateWithoutTemplateInput[]
  connectOrCreate?: Prisma.ReminderHistoryCreateOrConnectWithoutTemplateInput | Prisma.ReminderHistoryCreateOrConnectWithoutTemplateInput[]
  createMany?: Prisma.ReminderHistoryCreateManyTemplateInputEnvelope
  connect?: Prisma.ReminderHistoryWhereUniqueInput | Prisma.ReminderHistoryWhereUniqueInput[]
}

export type ReminderHistoryUncheckedCreateNestedManyWithoutTemplateInput = {
  create?: Prisma.XOR<Prisma.ReminderHistoryCreateWithoutTemplateInput, Prisma.ReminderHistoryUncheckedCreateWithoutTemplateInput> | Prisma.ReminderHistoryCreateWithoutTemplateInput[] | Prisma.ReminderHistoryUncheckedCreateWithoutTemplateInput[]
  connectOrCreate?: Prisma.ReminderHistoryCreateOrConnectWithoutTemplateInput | Prisma.ReminderHistoryCreateOrConnectWithoutTemplateInput[]
  createMany?: Prisma.ReminderHistoryCreateManyTemplateInputEnvelope
  connect?: Prisma.ReminderHistoryWhereUniqueInput | Prisma.ReminderHistoryWhereUniqueInput[]
}

export type ReminderHistoryUpdateManyWithoutTemplateNestedInput = {
  create?: Prisma.XOR<Prisma.ReminderHistoryCreateWithoutTemplateInput, Prisma.ReminderHistoryUncheckedCreateWithoutTemplateInput> | Prisma.ReminderHistoryCreateWithoutTemplateInput[] | Prisma.ReminderHistoryUncheckedCreateWithoutTemplateInput[]
  connectOrCreate?: Prisma.ReminderHistoryCreateOrConnectWithoutTemplateInput | Prisma.ReminderHistoryCreateOrConnectWithoutTemplateInput[]
  upsert?: Prisma.ReminderHistoryUpsertWithWhereUniqueWithoutTemplateInput | Prisma.ReminderHistoryUpsertWithWhereUniqueWithoutTemplateInput[]
  createMany?: Prisma.ReminderHistoryCreateManyTemplateInputEnvelope
  set?: Prisma.ReminderHistoryWhereUniqueInput | Prisma.ReminderHistoryWhereUniqueInput[]
  disconnect?: Prisma.ReminderHistoryWhereUniqueInput | Prisma.ReminderHistoryWhereUniqueInput[]
  delete?: Prisma.ReminderHistoryWhereUniqueInput | Prisma.ReminderHistoryWhereUniqueInput[]
  connect?: Prisma.ReminderHistoryWhereUniqueInput | Prisma.ReminderHistoryWhereUniqueInput[]
  update?: Prisma.ReminderHistoryUpdateWithWhereUniqueWithoutTemplateInput | Prisma.ReminderHistoryUpdateWithWhereUniqueWithoutTemplateInput[]
  updateMany?: Prisma.ReminderHistoryUpdateManyWithWhereWithoutTemplateInput | Prisma.ReminderHistoryUpdateManyWithWhereWithoutTemplateInput[]
  deleteMany?: Prisma.ReminderHistoryScalarWhereInput | Prisma.ReminderHistoryScalarWhereInput[]
}

export type ReminderHistoryUncheckedUpdateManyWithoutTemplateNestedInput = {
  create?: Prisma.XOR<Prisma.ReminderHistoryCreateWithoutTemplateInput, Prisma.ReminderHistoryUncheckedCreateWithoutTemplateInput> | Prisma.ReminderHistoryCreateWithoutTemplateInput[] | Prisma.ReminderHistoryUncheckedCreateWithoutTemplateInput[]
  connectOrCreate?: Prisma.ReminderHistoryCreateOrConnectWithoutTemplateInput | Prisma.ReminderHistoryCreateOrConnectWithoutTemplateInput[]
  upsert?: Prisma.ReminderHistoryUpsertWithWhereUniqueWithoutTemplateInput | Prisma.ReminderHistoryUpsertWithWhereUniqueWithoutTemplateInput[]
  createMany?: Prisma.ReminderHistoryCreateManyTemplateInputEnvelope
  set?: Prisma.ReminderHistoryWhereUniqueInput | Prisma.ReminderHistoryWhereUniqueInput[]
  disconnect?: Prisma.ReminderHistoryWhereUniqueInput | Prisma.ReminderHistoryWhereUniqueInput[]
  delete?: Prisma.ReminderHistoryWhereUniqueInput | Prisma.ReminderHistoryWhereUniqueInput[]
  connect?: Prisma.ReminderHistoryWhereUniqueInput | Prisma.ReminderHistoryWhereUniqueInput[]
  update?: Prisma.ReminderHistoryUpdateWithWhereUniqueWithoutTemplateInput | Prisma.ReminderHistoryUpdateWithWhereUniqueWithoutTemplateInput[]
  updateMany?: Prisma.ReminderHistoryUpdateManyWithWhereWithoutTemplateInput | Prisma.ReminderHistoryUpdateManyWithWhereWithoutTemplateInput[]
  deleteMany?: Prisma.ReminderHistoryScalarWhereInput | Prisma.ReminderHistoryScalarWhereInput[]
}

export type ReminderHistoryCreateNestedManyWithoutTaskInput = {
  create?: Prisma.XOR<Prisma.ReminderHistoryCreateWithoutTaskInput, Prisma.ReminderHistoryUncheckedCreateWithoutTaskInput> | Prisma.ReminderHistoryCreateWithoutTaskInput[] | Prisma.ReminderHistoryUncheckedCreateWithoutTaskInput[]
  connectOrCreate?: Prisma.ReminderHistoryCreateOrConnectWithoutTaskInput | Prisma.ReminderHistoryCreateOrConnectWithoutTaskInput[]
  createMany?: Prisma.ReminderHistoryCreateManyTaskInputEnvelope
  connect?: Prisma.ReminderHistoryWhereUniqueInput | Prisma.ReminderHistoryWhereUniqueInput[]
}

export type ReminderHistoryUncheckedCreateNestedManyWithoutTaskInput = {
  create?: Prisma.XOR<Prisma.ReminderHistoryCreateWithoutTaskInput, Prisma.ReminderHistoryUncheckedCreateWithoutTaskInput> | Prisma.ReminderHistoryCreateWithoutTaskInput[] | Prisma.ReminderHistoryUncheckedCreateWithoutTaskInput[]
  connectOrCreate?: Prisma.ReminderHistoryCreateOrConnectWithoutTaskInput | Prisma.ReminderHistoryCreateOrConnectWithoutTaskInput[]
  createMany?: Prisma.ReminderHistoryCreateManyTaskInputEnvelope
  connect?: Prisma.ReminderHistoryWhereUniqueInput | Prisma.ReminderHistoryWhereUniqueInput[]
}

export type ReminderHistoryUpdateManyWithoutTaskNestedInput = {
  create?: Prisma.XOR<Prisma.ReminderHistoryCreateWithoutTaskInput, Prisma.ReminderHistoryUncheckedCreateWithoutTaskInput> | Prisma.ReminderHistoryCreateWithoutTaskInput[] | Prisma.ReminderHistoryUncheckedCreateWithoutTaskInput[]
  connectOrCreate?: Prisma.ReminderHistoryCreateOrConnectWithoutTaskInput | Prisma.ReminderHistoryCreateOrConnectWithoutTaskInput[]
  upsert?: Prisma.ReminderHistoryUpsertWithWhereUniqueWithoutTaskInput | Prisma.ReminderHistoryUpsertWithWhereUniqueWithoutTaskInput[]
  createMany?: Prisma.ReminderHistoryCreateManyTaskInputEnvelope
  set?: Prisma.ReminderHistoryWhereUniqueInput | Prisma.ReminderHistoryWhereUniqueInput[]
  disconnect?: Prisma.ReminderHistoryWhereUniqueInput | Prisma.ReminderHistoryWhereUniqueInput[]
  delete?: Prisma.ReminderHistoryWhereUniqueInput | Prisma.ReminderHistoryWhereUniqueInput[]
  connect?: Prisma.ReminderHistoryWhereUniqueInput | Prisma.ReminderHistoryWhereUniqueInput[]
  update?: Prisma.ReminderHistoryUpdateWithWhereUniqueWithoutTaskInput | Prisma.ReminderHistoryUpdateWithWhereUniqueWithoutTaskInput[]
  updateMany?: Prisma.ReminderHistoryUpdateManyWithWhereWithoutTaskInput | Prisma.ReminderHistoryUpdateManyWithWhereWithoutTaskInput[]
  deleteMany?: Prisma.ReminderHistoryScalarWhereInput | Prisma.ReminderHistoryScalarWhereInput[]
}

export type ReminderHistoryUncheckedUpdateManyWithoutTaskNestedInput = {
  create?: Prisma.XOR<Prisma.ReminderHistoryCreateWithoutTaskInput, Prisma.ReminderHistoryUncheckedCreateWithoutTaskInput> | Prisma.ReminderHistoryCreateWithoutTaskInput[] | Prisma.ReminderHistoryUncheckedCreateWithoutTaskInput[]
  connectOrCreate?: Prisma.ReminderHistoryCreateOrConnectWithoutTaskInput | Prisma.ReminderHistoryCreateOrConnectWithoutTaskInput[]
  upsert?: Prisma.ReminderHistoryUpsertWithWhereUniqueWithoutTaskInput | Prisma.ReminderHistoryUpsertWithWhereUniqueWithoutTaskInput[]
  createMany?: Prisma.ReminderHistoryCreateManyTaskInputEnvelope
  set?: Prisma.ReminderHistoryWhereUniqueInput | Prisma.ReminderHistoryWhereUniqueInput[]
  disconnect?: Prisma.ReminderHistoryWhereUniqueInput | Prisma.ReminderHistoryWhereUniqueInput[]
  delete?: Prisma.ReminderHistoryWhereUniqueInput | Prisma.ReminderHistoryWhereUniqueInput[]
  connect?: Prisma.ReminderHistoryWhereUniqueInput | Prisma.ReminderHistoryWhereUniqueInput[]
  update?: Prisma.ReminderHistoryUpdateWithWhereUniqueWithoutTaskInput | Prisma.ReminderHistoryUpdateWithWhereUniqueWithoutTaskInput[]
  updateMany?: Prisma.ReminderHistoryUpdateManyWithWhereWithoutTaskInput | Prisma.ReminderHistoryUpdateManyWithWhereWithoutTaskInput[]
  deleteMany?: Prisma.ReminderHistoryScalarWhereInput | Prisma.ReminderHistoryScalarWhereInput[]
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}

export type ReminderHistoryCreateWithoutTemplateInput = {
  id?: string
  taskTitle: string
  templateName?: string | null
  date: string
  time: string
  status: string
  sentAt?: Date | string | null
  createdAt?: Date | string
  task: Prisma.TaskCreateNestedOneWithoutReminderHistoriesInput
}

export type ReminderHistoryUncheckedCreateWithoutTemplateInput = {
  id?: string
  taskTitle: string
  templateName?: string | null
  date: string
  time: string
  status: string
  sentAt?: Date | string | null
  createdAt?: Date | string
  taskId: string
}

export type ReminderHistoryCreateOrConnectWithoutTemplateInput = {
  where: Prisma.ReminderHistoryWhereUniqueInput
  create: Prisma.XOR<Prisma.ReminderHistoryCreateWithoutTemplateInput, Prisma.ReminderHistoryUncheckedCreateWithoutTemplateInput>
}

export type ReminderHistoryCreateManyTemplateInputEnvelope = {
  data: Prisma.ReminderHistoryCreateManyTemplateInput | Prisma.ReminderHistoryCreateManyTemplateInput[]
}

export type ReminderHistoryUpsertWithWhereUniqueWithoutTemplateInput = {
  where: Prisma.ReminderHistoryWhereUniqueInput
  update: Prisma.XOR<Prisma.ReminderHistoryUpdateWithoutTemplateInput, Prisma.ReminderHistoryUncheckedUpdateWithoutTemplateInput>
  create: Prisma.XOR<Prisma.ReminderHistoryCreateWithoutTemplateInput, Prisma.ReminderHistoryUncheckedCreateWithoutTemplateInput>
}

export type ReminderHistoryUpdateWithWhereUniqueWithoutTemplateInput = {
  where: Prisma.ReminderHistoryWhereUniqueInput
  data: Prisma.XOR<Prisma.ReminderHistoryUpdateWithoutTemplateInput, Prisma.ReminderHistoryUncheckedUpdateWithoutTemplateInput>
}

export type ReminderHistoryUpdateManyWithWhereWithoutTemplateInput = {
  where: Prisma.ReminderHistoryScalarWhereInput
  data: Prisma.XOR<Prisma.ReminderHistoryUpdateManyMutationInput, Prisma.ReminderHistoryUncheckedUpdateManyWithoutTemplateInput>
}

export type ReminderHistoryScalarWhereInput = {
  AND?: Prisma.ReminderHistoryScalarWhereInput | Prisma.ReminderHistoryScalarWhereInput[]
  OR?: Prisma.ReminderHistoryScalarWhereInput[]
  NOT?: Prisma.ReminderHistoryScalarWhereInput | Prisma.ReminderHistoryScalarWhereInput[]
  id?: Prisma.StringFilter<"ReminderHistory"> | string
  taskTitle?: Prisma.StringFilter<"ReminderHistory"> | string
  templateName?: Prisma.StringNullableFilter<"ReminderHistory"> | string | null
  date?: Prisma.StringFilter<"ReminderHistory"> | string
  time?: Prisma.StringFilter<"ReminderHistory"> | string
  status?: Prisma.StringFilter<"ReminderHistory"> | string
  sentAt?: Prisma.DateTimeNullableFilter<"ReminderHistory"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"ReminderHistory"> | Date | string
  taskId?: Prisma.StringFilter<"ReminderHistory"> | string
  templateId?: Prisma.StringNullableFilter<"ReminderHistory"> | string | null
}

export type ReminderHistoryCreateWithoutTaskInput = {
  id?: string
  taskTitle: string
  templateName?: string | null
  date: string
  time: string
  status: string
  sentAt?: Date | string | null
  createdAt?: Date | string
  template?: Prisma.TemplateCreateNestedOneWithoutReminderHistoriesInput
}

export type ReminderHistoryUncheckedCreateWithoutTaskInput = {
  id?: string
  taskTitle: string
  templateName?: string | null
  date: string
  time: string
  status: string
  sentAt?: Date | string | null
  createdAt?: Date | string
  templateId?: string | null
}

export type ReminderHistoryCreateOrConnectWithoutTaskInput = {
  where: Prisma.ReminderHistoryWhereUniqueInput
  create: Prisma.XOR<Prisma.ReminderHistoryCreateWithoutTaskInput, Prisma.ReminderHistoryUncheckedCreateWithoutTaskInput>
}

export type ReminderHistoryCreateManyTaskInputEnvelope = {
  data: Prisma.ReminderHistoryCreateManyTaskInput | Prisma.ReminderHistoryCreateManyTaskInput[]
}

export type ReminderHistoryUpsertWithWhereUniqueWithoutTaskInput = {
  where: Prisma.ReminderHistoryWhereUniqueInput
  update: Prisma.XOR<Prisma.ReminderHistoryUpdateWithoutTaskInput, Prisma.ReminderHistoryUncheckedUpdateWithoutTaskInput>
  create: Prisma.XOR<Prisma.ReminderHistoryCreateWithoutTaskInput, Prisma.ReminderHistoryUncheckedCreateWithoutTaskInput>
}

export type ReminderHistoryUpdateWithWhereUniqueWithoutTaskInput = {
  where: Prisma.ReminderHistoryWhereUniqueInput
  data: Prisma.XOR<Prisma.ReminderHistoryUpdateWithoutTaskInput, Prisma.ReminderHistoryUncheckedUpdateWithoutTaskInput>
}

export type ReminderHistoryUpdateManyWithWhereWithoutTaskInput = {
  where: Prisma.ReminderHistoryScalarWhereInput
  data: Prisma.XOR<Prisma.ReminderHistoryUpdateManyMutationInput, Prisma.ReminderHistoryUncheckedUpdateManyWithoutTaskInput>
}

export type ReminderHistoryCreateManyTemplateInput = {
  id?: string
  taskTitle: string
  templateName?: string | null
  date: string
  time: string
  status: string
  sentAt?: Date | string | null
  createdAt?: Date | string
  taskId: string
}

export type ReminderHistoryUpdateWithoutTemplateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  taskTitle?: Prisma.StringFieldUpdateOperationsInput | string
  templateName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  date?: Prisma.StringFieldUpdateOperationsInput | string
  time?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  sentAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  task?: Prisma.TaskUpdateOneRequiredWithoutReminderHistoriesNestedInput
}

export type ReminderHistoryUncheckedUpdateWithoutTemplateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  taskTitle?: Prisma.StringFieldUpdateOperationsInput | string
  templateName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  date?: Prisma.StringFieldUpdateOperationsInput | string
  time?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  sentAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  taskId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ReminderHistoryUncheckedUpdateManyWithoutTemplateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  taskTitle?: Prisma.StringFieldUpdateOperationsInput | string
  templateName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  date?: Prisma.StringFieldUpdateOperationsInput | string
  time?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  sentAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  taskId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ReminderHistoryCreateManyTaskInput = {
  id?: string
  taskTitle: string
  templateName?: string | null
  date: string
  time: string
  status: string
  sentAt?: Date | string | null
  createdAt?: Date | string
  templateId?: string | null
}

export type ReminderHistoryUpdateWithoutTaskInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  taskTitle?: Prisma.StringFieldUpdateOperationsInput | string
  templateName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  date?: Prisma.StringFieldUpdateOperationsInput | string
  time?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  sentAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  template?: Prisma.TemplateUpdateOneWithoutReminderHistoriesNestedInput
}

export type ReminderHistoryUncheckedUpdateWithoutTaskInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  taskTitle?: Prisma.StringFieldUpdateOperationsInput | string
  templateName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  date?: Prisma.StringFieldUpdateOperationsInput | string
  time?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  sentAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  templateId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ReminderHistoryUncheckedUpdateManyWithoutTaskInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  taskTitle?: Prisma.StringFieldUpdateOperationsInput | string
  templateName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  date?: Prisma.StringFieldUpdateOperationsInput | string
  time?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  sentAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  templateId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}



export type ReminderHistorySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  taskTitle?: boolean
  templateName?: boolean
  date?: boolean
  time?: boolean
  status?: boolean
  sentAt?: boolean
  createdAt?: boolean
  taskId?: boolean
  templateId?: boolean
  task?: boolean | Prisma.TaskDefaultArgs<ExtArgs>
  template?: boolean | Prisma.ReminderHistory$templateArgs<ExtArgs>
}, ExtArgs["result"]["reminderHistory"]>

export type ReminderHistorySelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  taskTitle?: boolean
  templateName?: boolean
  date?: boolean
  time?: boolean
  status?: boolean
  sentAt?: boolean
  createdAt?: boolean
  taskId?: boolean
  templateId?: boolean
  task?: boolean | Prisma.TaskDefaultArgs<ExtArgs>
  template?: boolean | Prisma.ReminderHistory$templateArgs<ExtArgs>
}, ExtArgs["result"]["reminderHistory"]>

export type ReminderHistorySelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  taskTitle?: boolean
  templateName?: boolean
  date?: boolean
  time?: boolean
  status?: boolean
  sentAt?: boolean
  createdAt?: boolean
  taskId?: boolean
  templateId?: boolean
  task?: boolean | Prisma.TaskDefaultArgs<ExtArgs>
  template?: boolean | Prisma.ReminderHistory$templateArgs<ExtArgs>
}, ExtArgs["result"]["reminderHistory"]>

export type ReminderHistorySelectScalar = {
  id?: boolean
  taskTitle?: boolean
  templateName?: boolean
  date?: boolean
  time?: boolean
  status?: boolean
  sentAt?: boolean
  createdAt?: boolean
  taskId?: boolean
  templateId?: boolean
}

export type ReminderHistoryOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "taskTitle" | "templateName" | "date" | "time" | "status" | "sentAt" | "createdAt" | "taskId" | "templateId", ExtArgs["result"]["reminderHistory"]>
export type ReminderHistoryInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  task?: boolean | Prisma.TaskDefaultArgs<ExtArgs>
  template?: boolean | Prisma.ReminderHistory$templateArgs<ExtArgs>
}
export type ReminderHistoryIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  task?: boolean | Prisma.TaskDefaultArgs<ExtArgs>
  template?: boolean | Prisma.ReminderHistory$templateArgs<ExtArgs>
}
export type ReminderHistoryIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  task?: boolean | Prisma.TaskDefaultArgs<ExtArgs>
  template?: boolean | Prisma.ReminderHistory$templateArgs<ExtArgs>
}

export type $ReminderHistoryPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ReminderHistory"
  objects: {
    task: Prisma.$TaskPayload<ExtArgs>
    template: Prisma.$TemplatePayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    taskTitle: string
    templateName: string | null
    date: string
    time: string
    status: string
    sentAt: Date | null
    createdAt: Date
    taskId: string
    templateId: string | null
  }, ExtArgs["result"]["reminderHistory"]>
  composites: {}
}

export type ReminderHistoryGetPayload<S extends boolean | null | undefined | ReminderHistoryDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ReminderHistoryPayload, S>

export type ReminderHistoryCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ReminderHistoryFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ReminderHistoryCountAggregateInputType | true
  }

export interface ReminderHistoryDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ReminderHistory'], meta: { name: 'ReminderHistory' } }
  /**
   * Find zero or one ReminderHistory that matches the filter.
   * @param {ReminderHistoryFindUniqueArgs} args - Arguments to find a ReminderHistory
   * @example
   * // Get one ReminderHistory
   * const reminderHistory = await prisma.reminderHistory.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ReminderHistoryFindUniqueArgs>(args: Prisma.SelectSubset<T, ReminderHistoryFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ReminderHistoryClient<runtime.Types.Result.GetResult<Prisma.$ReminderHistoryPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ReminderHistory that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ReminderHistoryFindUniqueOrThrowArgs} args - Arguments to find a ReminderHistory
   * @example
   * // Get one ReminderHistory
   * const reminderHistory = await prisma.reminderHistory.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ReminderHistoryFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ReminderHistoryFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ReminderHistoryClient<runtime.Types.Result.GetResult<Prisma.$ReminderHistoryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ReminderHistory that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReminderHistoryFindFirstArgs} args - Arguments to find a ReminderHistory
   * @example
   * // Get one ReminderHistory
   * const reminderHistory = await prisma.reminderHistory.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ReminderHistoryFindFirstArgs>(args?: Prisma.SelectSubset<T, ReminderHistoryFindFirstArgs<ExtArgs>>): Prisma.Prisma__ReminderHistoryClient<runtime.Types.Result.GetResult<Prisma.$ReminderHistoryPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ReminderHistory that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReminderHistoryFindFirstOrThrowArgs} args - Arguments to find a ReminderHistory
   * @example
   * // Get one ReminderHistory
   * const reminderHistory = await prisma.reminderHistory.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ReminderHistoryFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ReminderHistoryFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ReminderHistoryClient<runtime.Types.Result.GetResult<Prisma.$ReminderHistoryPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ReminderHistories that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReminderHistoryFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ReminderHistories
   * const reminderHistories = await prisma.reminderHistory.findMany()
   * 
   * // Get first 10 ReminderHistories
   * const reminderHistories = await prisma.reminderHistory.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const reminderHistoryWithIdOnly = await prisma.reminderHistory.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ReminderHistoryFindManyArgs>(args?: Prisma.SelectSubset<T, ReminderHistoryFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ReminderHistoryPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ReminderHistory.
   * @param {ReminderHistoryCreateArgs} args - Arguments to create a ReminderHistory.
   * @example
   * // Create one ReminderHistory
   * const ReminderHistory = await prisma.reminderHistory.create({
   *   data: {
   *     // ... data to create a ReminderHistory
   *   }
   * })
   * 
   */
  create<T extends ReminderHistoryCreateArgs>(args: Prisma.SelectSubset<T, ReminderHistoryCreateArgs<ExtArgs>>): Prisma.Prisma__ReminderHistoryClient<runtime.Types.Result.GetResult<Prisma.$ReminderHistoryPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ReminderHistories.
   * @param {ReminderHistoryCreateManyArgs} args - Arguments to create many ReminderHistories.
   * @example
   * // Create many ReminderHistories
   * const reminderHistory = await prisma.reminderHistory.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ReminderHistoryCreateManyArgs>(args?: Prisma.SelectSubset<T, ReminderHistoryCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ReminderHistories and returns the data saved in the database.
   * @param {ReminderHistoryCreateManyAndReturnArgs} args - Arguments to create many ReminderHistories.
   * @example
   * // Create many ReminderHistories
   * const reminderHistory = await prisma.reminderHistory.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ReminderHistories and only return the `id`
   * const reminderHistoryWithIdOnly = await prisma.reminderHistory.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ReminderHistoryCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ReminderHistoryCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ReminderHistoryPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ReminderHistory.
   * @param {ReminderHistoryDeleteArgs} args - Arguments to delete one ReminderHistory.
   * @example
   * // Delete one ReminderHistory
   * const ReminderHistory = await prisma.reminderHistory.delete({
   *   where: {
   *     // ... filter to delete one ReminderHistory
   *   }
   * })
   * 
   */
  delete<T extends ReminderHistoryDeleteArgs>(args: Prisma.SelectSubset<T, ReminderHistoryDeleteArgs<ExtArgs>>): Prisma.Prisma__ReminderHistoryClient<runtime.Types.Result.GetResult<Prisma.$ReminderHistoryPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ReminderHistory.
   * @param {ReminderHistoryUpdateArgs} args - Arguments to update one ReminderHistory.
   * @example
   * // Update one ReminderHistory
   * const reminderHistory = await prisma.reminderHistory.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ReminderHistoryUpdateArgs>(args: Prisma.SelectSubset<T, ReminderHistoryUpdateArgs<ExtArgs>>): Prisma.Prisma__ReminderHistoryClient<runtime.Types.Result.GetResult<Prisma.$ReminderHistoryPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ReminderHistories.
   * @param {ReminderHistoryDeleteManyArgs} args - Arguments to filter ReminderHistories to delete.
   * @example
   * // Delete a few ReminderHistories
   * const { count } = await prisma.reminderHistory.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ReminderHistoryDeleteManyArgs>(args?: Prisma.SelectSubset<T, ReminderHistoryDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ReminderHistories.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReminderHistoryUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ReminderHistories
   * const reminderHistory = await prisma.reminderHistory.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ReminderHistoryUpdateManyArgs>(args: Prisma.SelectSubset<T, ReminderHistoryUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ReminderHistories and returns the data updated in the database.
   * @param {ReminderHistoryUpdateManyAndReturnArgs} args - Arguments to update many ReminderHistories.
   * @example
   * // Update many ReminderHistories
   * const reminderHistory = await prisma.reminderHistory.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ReminderHistories and only return the `id`
   * const reminderHistoryWithIdOnly = await prisma.reminderHistory.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ReminderHistoryUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ReminderHistoryUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ReminderHistoryPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ReminderHistory.
   * @param {ReminderHistoryUpsertArgs} args - Arguments to update or create a ReminderHistory.
   * @example
   * // Update or create a ReminderHistory
   * const reminderHistory = await prisma.reminderHistory.upsert({
   *   create: {
   *     // ... data to create a ReminderHistory
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ReminderHistory we want to update
   *   }
   * })
   */
  upsert<T extends ReminderHistoryUpsertArgs>(args: Prisma.SelectSubset<T, ReminderHistoryUpsertArgs<ExtArgs>>): Prisma.Prisma__ReminderHistoryClient<runtime.Types.Result.GetResult<Prisma.$ReminderHistoryPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ReminderHistories.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReminderHistoryCountArgs} args - Arguments to filter ReminderHistories to count.
   * @example
   * // Count the number of ReminderHistories
   * const count = await prisma.reminderHistory.count({
   *   where: {
   *     // ... the filter for the ReminderHistories we want to count
   *   }
   * })
  **/
  count<T extends ReminderHistoryCountArgs>(
    args?: Prisma.Subset<T, ReminderHistoryCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ReminderHistoryCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ReminderHistory.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReminderHistoryAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ReminderHistoryAggregateArgs>(args: Prisma.Subset<T, ReminderHistoryAggregateArgs>): Prisma.PrismaPromise<GetReminderHistoryAggregateType<T>>

  /**
   * Group by ReminderHistory.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReminderHistoryGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ReminderHistoryGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ReminderHistoryGroupByArgs['orderBy'] }
      : { orderBy?: ReminderHistoryGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ReminderHistoryGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetReminderHistoryGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ReminderHistory model
 */
readonly fields: ReminderHistoryFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ReminderHistory.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ReminderHistoryClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  task<T extends Prisma.TaskDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TaskDefaultArgs<ExtArgs>>): Prisma.Prisma__TaskClient<runtime.Types.Result.GetResult<Prisma.$TaskPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  template<T extends Prisma.ReminderHistory$templateArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ReminderHistory$templateArgs<ExtArgs>>): Prisma.Prisma__TemplateClient<runtime.Types.Result.GetResult<Prisma.$TemplatePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ReminderHistory model
 */
export interface ReminderHistoryFieldRefs {
  readonly id: Prisma.FieldRef<"ReminderHistory", 'String'>
  readonly taskTitle: Prisma.FieldRef<"ReminderHistory", 'String'>
  readonly templateName: Prisma.FieldRef<"ReminderHistory", 'String'>
  readonly date: Prisma.FieldRef<"ReminderHistory", 'String'>
  readonly time: Prisma.FieldRef<"ReminderHistory", 'String'>
  readonly status: Prisma.FieldRef<"ReminderHistory", 'String'>
  readonly sentAt: Prisma.FieldRef<"ReminderHistory", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"ReminderHistory", 'DateTime'>
  readonly taskId: Prisma.FieldRef<"ReminderHistory", 'String'>
  readonly templateId: Prisma.FieldRef<"ReminderHistory", 'String'>
}
    

// Custom InputTypes
/**
 * ReminderHistory findUnique
 */
export type ReminderHistoryFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReminderHistory
   */
  select?: Prisma.ReminderHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReminderHistory
   */
  omit?: Prisma.ReminderHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReminderHistoryInclude<ExtArgs> | null
  /**
   * Filter, which ReminderHistory to fetch.
   */
  where: Prisma.ReminderHistoryWhereUniqueInput
}

/**
 * ReminderHistory findUniqueOrThrow
 */
export type ReminderHistoryFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReminderHistory
   */
  select?: Prisma.ReminderHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReminderHistory
   */
  omit?: Prisma.ReminderHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReminderHistoryInclude<ExtArgs> | null
  /**
   * Filter, which ReminderHistory to fetch.
   */
  where: Prisma.ReminderHistoryWhereUniqueInput
}

/**
 * ReminderHistory findFirst
 */
export type ReminderHistoryFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReminderHistory
   */
  select?: Prisma.ReminderHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReminderHistory
   */
  omit?: Prisma.ReminderHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReminderHistoryInclude<ExtArgs> | null
  /**
   * Filter, which ReminderHistory to fetch.
   */
  where?: Prisma.ReminderHistoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ReminderHistories to fetch.
   */
  orderBy?: Prisma.ReminderHistoryOrderByWithRelationInput | Prisma.ReminderHistoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ReminderHistories.
   */
  cursor?: Prisma.ReminderHistoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ReminderHistories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ReminderHistories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ReminderHistories.
   */
  distinct?: Prisma.ReminderHistoryScalarFieldEnum | Prisma.ReminderHistoryScalarFieldEnum[]
}

/**
 * ReminderHistory findFirstOrThrow
 */
export type ReminderHistoryFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReminderHistory
   */
  select?: Prisma.ReminderHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReminderHistory
   */
  omit?: Prisma.ReminderHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReminderHistoryInclude<ExtArgs> | null
  /**
   * Filter, which ReminderHistory to fetch.
   */
  where?: Prisma.ReminderHistoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ReminderHistories to fetch.
   */
  orderBy?: Prisma.ReminderHistoryOrderByWithRelationInput | Prisma.ReminderHistoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ReminderHistories.
   */
  cursor?: Prisma.ReminderHistoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ReminderHistories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ReminderHistories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ReminderHistories.
   */
  distinct?: Prisma.ReminderHistoryScalarFieldEnum | Prisma.ReminderHistoryScalarFieldEnum[]
}

/**
 * ReminderHistory findMany
 */
export type ReminderHistoryFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReminderHistory
   */
  select?: Prisma.ReminderHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReminderHistory
   */
  omit?: Prisma.ReminderHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReminderHistoryInclude<ExtArgs> | null
  /**
   * Filter, which ReminderHistories to fetch.
   */
  where?: Prisma.ReminderHistoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ReminderHistories to fetch.
   */
  orderBy?: Prisma.ReminderHistoryOrderByWithRelationInput | Prisma.ReminderHistoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ReminderHistories.
   */
  cursor?: Prisma.ReminderHistoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ReminderHistories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ReminderHistories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ReminderHistories.
   */
  distinct?: Prisma.ReminderHistoryScalarFieldEnum | Prisma.ReminderHistoryScalarFieldEnum[]
}

/**
 * ReminderHistory create
 */
export type ReminderHistoryCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReminderHistory
   */
  select?: Prisma.ReminderHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReminderHistory
   */
  omit?: Prisma.ReminderHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReminderHistoryInclude<ExtArgs> | null
  /**
   * The data needed to create a ReminderHistory.
   */
  data: Prisma.XOR<Prisma.ReminderHistoryCreateInput, Prisma.ReminderHistoryUncheckedCreateInput>
}

/**
 * ReminderHistory createMany
 */
export type ReminderHistoryCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ReminderHistories.
   */
  data: Prisma.ReminderHistoryCreateManyInput | Prisma.ReminderHistoryCreateManyInput[]
}

/**
 * ReminderHistory createManyAndReturn
 */
export type ReminderHistoryCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReminderHistory
   */
  select?: Prisma.ReminderHistorySelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ReminderHistory
   */
  omit?: Prisma.ReminderHistoryOmit<ExtArgs> | null
  /**
   * The data used to create many ReminderHistories.
   */
  data: Prisma.ReminderHistoryCreateManyInput | Prisma.ReminderHistoryCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReminderHistoryIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ReminderHistory update
 */
export type ReminderHistoryUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReminderHistory
   */
  select?: Prisma.ReminderHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReminderHistory
   */
  omit?: Prisma.ReminderHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReminderHistoryInclude<ExtArgs> | null
  /**
   * The data needed to update a ReminderHistory.
   */
  data: Prisma.XOR<Prisma.ReminderHistoryUpdateInput, Prisma.ReminderHistoryUncheckedUpdateInput>
  /**
   * Choose, which ReminderHistory to update.
   */
  where: Prisma.ReminderHistoryWhereUniqueInput
}

/**
 * ReminderHistory updateMany
 */
export type ReminderHistoryUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ReminderHistories.
   */
  data: Prisma.XOR<Prisma.ReminderHistoryUpdateManyMutationInput, Prisma.ReminderHistoryUncheckedUpdateManyInput>
  /**
   * Filter which ReminderHistories to update
   */
  where?: Prisma.ReminderHistoryWhereInput
  /**
   * Limit how many ReminderHistories to update.
   */
  limit?: number
}

/**
 * ReminderHistory updateManyAndReturn
 */
export type ReminderHistoryUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReminderHistory
   */
  select?: Prisma.ReminderHistorySelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ReminderHistory
   */
  omit?: Prisma.ReminderHistoryOmit<ExtArgs> | null
  /**
   * The data used to update ReminderHistories.
   */
  data: Prisma.XOR<Prisma.ReminderHistoryUpdateManyMutationInput, Prisma.ReminderHistoryUncheckedUpdateManyInput>
  /**
   * Filter which ReminderHistories to update
   */
  where?: Prisma.ReminderHistoryWhereInput
  /**
   * Limit how many ReminderHistories to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReminderHistoryIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ReminderHistory upsert
 */
export type ReminderHistoryUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReminderHistory
   */
  select?: Prisma.ReminderHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReminderHistory
   */
  omit?: Prisma.ReminderHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReminderHistoryInclude<ExtArgs> | null
  /**
   * The filter to search for the ReminderHistory to update in case it exists.
   */
  where: Prisma.ReminderHistoryWhereUniqueInput
  /**
   * In case the ReminderHistory found by the `where` argument doesn't exist, create a new ReminderHistory with this data.
   */
  create: Prisma.XOR<Prisma.ReminderHistoryCreateInput, Prisma.ReminderHistoryUncheckedCreateInput>
  /**
   * In case the ReminderHistory was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ReminderHistoryUpdateInput, Prisma.ReminderHistoryUncheckedUpdateInput>
}

/**
 * ReminderHistory delete
 */
export type ReminderHistoryDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReminderHistory
   */
  select?: Prisma.ReminderHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReminderHistory
   */
  omit?: Prisma.ReminderHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReminderHistoryInclude<ExtArgs> | null
  /**
   * Filter which ReminderHistory to delete.
   */
  where: Prisma.ReminderHistoryWhereUniqueInput
}

/**
 * ReminderHistory deleteMany
 */
export type ReminderHistoryDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ReminderHistories to delete
   */
  where?: Prisma.ReminderHistoryWhereInput
  /**
   * Limit how many ReminderHistories to delete.
   */
  limit?: number
}

/**
 * ReminderHistory.template
 */
export type ReminderHistory$templateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Template
   */
  select?: Prisma.TemplateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Template
   */
  omit?: Prisma.TemplateOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TemplateInclude<ExtArgs> | null
  where?: Prisma.TemplateWhereInput
}

/**
 * ReminderHistory without action
 */
export type ReminderHistoryDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReminderHistory
   */
  select?: Prisma.ReminderHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReminderHistory
   */
  omit?: Prisma.ReminderHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReminderHistoryInclude<ExtArgs> | null
}
